baseURL = "https://www.lynnux.org/"
title = "Lynne Cure"

theme = "anubis"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

## Change this two to switch between different language
languageCode = "en"  # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "en"  # For HTML page, now support: en, zh-hans, zh-hant, ja, nl

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
paginate = 10


[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  author = "Lynne Cure" # You can also set author in post front matter individually
  subTitle = "Backend dev with diverse skillset"

  customCSS = ["css/my.css"]

  style="light"

  # Copyright
  copyrightStartYear = "2021"

  # Posts shown in homepage
  mainSections = ["post"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/Spirati"
    weight = 1
  [[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/_lynnux"
    weight = 2
  [[menu.footer]]
    name = "Discord Profile"
    url = "http://discord.com/users/365506149619073025"
    weight = 3
